token: "abcd" # Github API key
username: "krishnaiyer"
repositories:
  - name: "ghpm"
    username: "" # Overrides the global username
  # - name: "helm-gopg"
  #   username: "" # Overrides the global username
